language: python

python:
  - '3.4'
  - '3.5'
  - 'nightly'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jpegoptim
  - wget --no-check-certificate http://pngquant.org/pngquant_1.7.1-1_i386.deb
  - sudo dpkg -i pngquant_1.7.1-1_i386.deb

install: pip install -e .

script: python setup.py test
